language: php

php:
  - 5.4
  - 5.5

env:
  - APPLICATION_ENV="testing" DB="mysql" DB_USERNAME="root"

before_install:
  - mysql -u$DB_USERNAME -e 'create database bazalt_cms;'
  - mysql -u$DB_USERNAME bazalt_cms < install.sql
  - echo "INSERT INTO `cms_users` (`id`, `login`, `password`, `firstname`, `secondname`, `patronymic`, `gender`, `birth_date`, `email`, `created_at`, `is_active`, `last_activity`, `session_id`, `is_god`) VALUES (1, 'admin', '4dff4ea340f0a823f15d3f4f01ab62eae0e5da579ccb851f8db9dfe84c58b2b37b89903a740e1ee172da793a6e79d560e5f7f9bd058a12a280433ed6fa46510a', 'Administrator', NULL, NULL, 'unknown', NULL, NULL, '2013-04-23 11:13:01', 1, '2013-09-14 09:50:30', NULL, 1);" | mysql -u root
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('awdawd') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

before_script:
  - composer self-update
  - composer install --dev --no-interaction

script:
  - mkdir -p tmp/logs
  - mkdir -p build/logs
  - phpunit --configuration phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls -v